AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "db/dummy_data/**/*"
  DisplayCopNames: true

Metrics/AbcSize: 
  Max: 25

Metrics/BlockLength:
  Max: 26

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

