version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - node-modules-volume:/app/node_modules
      - bundle-volume:/usr/local/bundle
    ports:
      - 3030:3000
    tty: true
    stdin_open: true
    environment:
      RDS_HOSTNAME: $RDS_HOSTNAME
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
      USER_TABLE: $USER_TABLE
      USER_NAME_ATTRIBUTE: $USER_NAME_ATTRIBUTE
    networks:
      - external.group
  matomo:
    image: matomo:latest
    platform: linux/x86_64
    ports:
      - "80:80"
    environment:
      MATOMO_DATABASE_HOST: $RDS_HOSTNAME
      MATOMO_DATABASE_DBNAME: $RDS_DB_NAME
      MATOMO_DATABASE_USERNAME: $RDS_USERNAME
      MATOMO_DATABASE_PASSWORD: $RDS_PASSWORD
    networks:
      - external.group
volumes:
  bundle-volume:
  node-modules-volume:
networks:
  external.group:
    external: true
